-- Create Database
-- This script creates the main database for the project

CREATE DATABASE IF NOT EXISTS MY_DATABASE;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS MY_DATABASE.RAW_DATA;
CREATE SCHEMA IF NOT EXISTS MY_DATABASE.STAGING;
CREATE SCHEMA IF NOT EXISTS MY_DATABASE.ANALYTICS;

-- Grant usage on database
GRANT USAGE ON DATABASE MY_DATABASE TO ROLE PUBLIC;
