-- Sample Table Creation
-- This script contains example table definitions

-- Create a sample customers table
CREATE TABLE IF NOT EXISTS MY_DATABASE.RAW_DATA.CUSTOMERS (
    CUSTOMER_ID NUMBER(38,0) PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(20),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_DATE TIMESTAMP_NTZ
);

-- Create a sample orders table
CREATE TABLE IF NOT EXISTS MY_DATABASE.RAW_DATA.ORDERS (
    ORDER_ID NUMBER(38,0) PRIMARY KEY,
    CUSTOMER_ID NUMBER(38,0),
    ORDER_DATE DATE,
    ORDER_AMOUNT NUMBER(10,2),
    STATUS VARCHAR(50),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES MY_DATABASE.RAW_DATA.CUSTOMERS(CUSTOMER_ID)
);

-- Create a sample products table
CREATE TABLE IF NOT EXISTS MY_DATABASE.RAW_DATA.PRODUCTS (
    PRODUCT_ID NUMBER(38,0) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255),
    CATEGORY VARCHAR(100),
    PRICE NUMBER(10,2),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
